steps:

  - name: 'java:8-alpine'
    args: ['./gradlew', 'uploadArchives']
#    env:
#      - '_MAVEN_USER=$_MAVEN_USER'
#      - '_MAVEN_PASS=$_MAVEN_PASS'

substitutions:
  _MAVEN_USER: user
  _MAVEN_PASS: pass

options:
  substitution_option: 'ALLOW_LOOSE'
