steps:

  - name: 'java:8-alpine'
    args: ['./gradlew', 'uploadArchives']
    env:
      - '_MAVEN_USER=$_MAVEN_USER'
      - '_MAVEN_PASS=$_MAVEN_PASS'

substitutions:
  _MAVEN_USER: prenigma-jfrog
  _MAVEN_PASS: prenigma-jfrog

options:
  substitution_option: 'ALLOW_LOOSE'
